<?php
/**
 * @file
 * Code for the HNW Products feature.
 */

include_once 'hnw_products.features.inc';

/**
 * Implements hook_taxonomy_term_insert($term).
 */
function hnw_products_taxonomy_term_insert($term) {
  // FIXME Only act if vocabulary is product_categories.
  if ($term->vid == 3) {
    _hnw_products_update_category_relations($term);
  }
}

/**
 * Implements hook_taxonomy_term_update($term).
 */
function hnw_products_taxonomy_term_update($term) {
  // FIXME Only act if vocabulary is product_categories.
  if ($term->vid == 3) {
    _hnw_products_update_category_relations($term);
  }
}

/**
 * After saving a product category term, update the relationships between
 * industries and applications in the term's field collections.
 */
function _hnw_products_update_category_relations($term) {
  // Loop over industries for this product category and fetch entity_id of
  // industry-and-application field collections. For each field collection,
  // there is one industry and unlimited applications.
  $collections = _hnw_products_db_select('field_industries_and_application_value', 'field_data_field_industries_and_application', 'entity_id', $term->tid);
  foreach ($collections as $collection) {
    // Industry.
    $industries = _hnw_products_db_select('field_industries_tid', 'field_data_field_industries', 'entity_id', $collection->field_industries_and_application_value);
    foreach ($industries as $industry) {
      // Applications.
      $applications = _hnw_products_db_select('field_applications_tid', 'field_data_field_applications', 'entity_id', $collection->field_industries_and_application_value);
      foreach ($applications as $application) {
        // Assign industry as parent industry of application.
        dpm("Assigning Industry " . $industry->field_industries_tid . " as parent of Application " . $application->field_applications_tid);
        $fields = array('entity_type' => 'taxonomy_term',
          'bundle' => 'applications', 'deleted' => 0,
          'entity_id' => $application->field_applications_tid,
          'revision_id' => $application->field_applications_tid,
          'language' => und, 'delta' => 0,
          'field_parent_industries_target_id' => $industry->field_industries_tid);
        db_insert('field_data_field_parent_industries')->fields($fields)->execute(); 
      }
    }
  }
}

/**
 * Prepare and execute a select query on the database.
 *
 * @param $select_col
 *   Column to be selected
 * @param $query_tbl
 *   Table to be queried
 * @param $query_col
 *   Column to be queried
 * @param $query_val
 *   Value to compare
 *
 * @return $results
 *   Row of results from the select query
 */
function _hnw_products_db_select($select_col, $query_tbl, $query_col, $query_val) {
  $results = db_query("select $select_col from $query_tbl where $query_col = :query_val", 
    array(':query_val' => $query_val));
  return $results;
}
